// language file
#ifndef _H_LANG_HEADER
#define _H_LANG_HEADER
#define LOC_CHAPITRE 1
#define LOC_CHAP_2_SOUSTITRE 2
#define LOC_MENU_APPUYEZ_TOUCHE 3
#define LOC_MENU_NEW_GAME 4
#define LOC_MENU_CONTINUER 5
#define LOC_MENU_OPTIONS 6
#define LOC_MENU_QUITTER 7
#endif
