// language file
#ifndef _H_LANG_HEADER
#define _H_LANG_HEADER
#define LOC_CHAPITRE 1
#define LOC_CHAP_2_SOUSTITRE 2
#define LOC_MENU_APPUYEZ_TOUCHE 3
#define LOC_MENU_NEW_GAME 4
#define LOC_MENU_NEW_GAME_HINT 5
#define LOC_MENU_CONTINUER 6
#define LOC_MENU_CONTINUER_HINT 7
#define LOC_MENU_OPTIONS 8
#define LOC_MENU_OPTIONS_HINT 9
#define LOC_MENU_QUITTER 10
#define LOC_MENU_QUITTER_HINT 11
#endif
